package:
  name: postgresql
  version: 9.4.4

source:
  fn: postgresql-9.4.4.tar.bz2
  url: https://ftp.postgresql.org/pub/source/v9.4.4/postgresql-9.4.4.tar.bz2
  md5: 1fe952c44ed26d7e6a335cf991a9c1c6
  patches:
    - prefer_ncurses_to_termcap.patch [not win]

build:
  number: 0

requirements:
  build:
    - python
    - perl [win]
    - gettext [win]
    - openssl
    - ncurses 6.0 [not win]
    - readline [not win]
    - libxml2
    - libxslt
  run:
    - python
    - openssl
    - ncurses 6.0 [not win]
    - readline [not win]
    - libxml2
    - libxslt

test:
  commands:
    - initdb --help
    - postgres --help
    - createdb --help
    - psql --help

about:
  home: http://www.postgresql.org
  license: PostgreSQL License

