diff --git Code/PgSQL/rdkit/Makefile Code/PgSQL/rdkit/Makefile
index 393a101..f9e116f 100644
--- Code/PgSQL/rdkit/Makefile
+++ Code/PgSQL/rdkit/Makefile
@@ -8,18 +8,20 @@
 # -------------------------
 
 
-RDKIT=$(RDBASE)
-
+RDKIT=$(PREFIX)
+USE_INCHI=1
+USE_AVALON=1
+STATIC_LINK=0
 
 ifeq ($(USE_INCHI),1)
   INCHILIBS=-lRDInchiLib -lInchi
-  INCHIFLAGS=-I${RDKIT}/External -DBUILD_INCHI_SUPPORT  
+  INCHIFLAGS=-DBUILD_INCHI_SUPPORT
   INCHIREGRESS=inchi
   USE_THREADS=1
 endif
 ifeq ($(USE_AVALON),1)
   AVALONLIBS=-lAvalonLib -lavalon_clib
-  AVALONFLAGS=-I${RDKIT}/External -DBUILD_AVALON_SUPPORT  
+  AVALONFLAGS=-DBUILD_AVALON_SUPPORT
   AVALONREGRESS=avalon
 endif
 
@@ -39,14 +41,11 @@ else
   SHLIB_LINK += -L${RDKIT}/lib $(addsuffix _static,${RDKLIBS})
 endif
 
-ifndef BOOSTHOME
-  BOOSTHOME=/usr/local
-endif
 SHLIB_LINK += -pthread
 
 SHLIB_LINK += ${THREADLIBS}
 
-PG_CPPFLAGS = -I${BOOSTHOME}/include -I${RDKIT}/Code -DRDKITVER='"007300"' ${AVALONFLAGS} ${INCHIFLAGS} ${POPCOUNTFLAGS}
+PG_CPPFLAGS = -I${PREFIX}/include -I${PREFIX}/include/rdkit -DRDKITVER='"007300"' ${AVALONFLAGS} ${INCHIFLAGS} ${POPCOUNTFLAGS}
 
 CPLUSPLUSFLAGS = $(filter-out -fexcess-precision=standard -Wmissing-prototypes -Wdeclaration-after-statement, $(CFLAGS))
 CPLUSPLUSFLAGS += -Wno-unused-function 
