package:
  name: rdkit-postgresql
  version: "__conda_version__"

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_rev: Release_2017_03
  patches:
    - cmakelists.txt.patch
    - adapter.cpp.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - python
    - msys2-conda-epoch >=20160418 [win]
    - m2-msys2-runtime [win]
    - m2-libiconv [win]
    - m2-libintl [win]
    - m2-diffutils [win]
    - m2-patch [win]
    - postgresql >=9.4,<9.5
    - rdkit >=2016.09
  run:
    - python
    - postgresql >=9.4,<9.5

about:
  home: http://rdkit.org
  license: BSD
