package:
  name: rdkit-postgresql
  version: "__conda_version__"

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_rev: Release_2016_09_2
  patches:
    - cmakelists.txt.patch
    - adapter.cpp.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - python
    - rdkit >=2016.09
    - postgresql >=9.4,<9.5
  run:
    - python
    - rdkit >=2016.09
    - postgresql >=9.4,<9.5

about:
  home: http://rdkit.org
  license: BSD
