package:
  name: rdkit-postgresql
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'LOCAL').replace("_", ".").replace("Release.","") }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_rev: Release_2019_09
  patches:
    - iostreams.patch [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - python
  host:
    - libboost {{ libboost }}
    - boost-cpp
    - eigen
    - msys2-conda-epoch >=20160418 [win]
    - m2-msys2-runtime [win]
    - m2-libiconv [win]
    - m2-libintl [win]
    - m2-diffutils [win]
    - m2-patch [win]
    - postgresql {{ postgresql }}
  run:
    - postgresql  {{ postgresql }}
    - libboost {{ libboost }}

about:
  home: http://rdkit.org
  license: BSD
