package:
    name: libxml2
    version: 2.9.4

source:
    git_url: https://github.com/winlibs/libxml2.git

build:
    number: 0

requirements:
    build:
      - iconv

about:
    home: https://github.com/winlibs/libxml2
    license: MIT
