package:
    name: libxslt
    version: 1.1.29

source:
    git_url: https://github.com/winlibs/libxslt.git

build:
    number: 0

requirements:
    build:
      - iconv
      - libxml2

about:
    home: https://github.com/winlibs/libxslt
    license: MIT
