package:
  name: rdkit-postgresql95
  version: "__conda_version__"

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_rev: Release_2017_09
  patches:
    - cmakelists.txt.patch
    - adapter.cpp.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - msys2-conda-epoch >=20160418 [win]
    - m2-msys2-runtime [win]
    - m2-libiconv [win]
    - m2-libintl [win]
    - m2-diffutils [win]
    - m2-patch [win]
    - rdkit >=2017.09
    - postgresql ==9.5
    - ncurses
    - nox [unix]
    - cairo [unix]
    - pkg-config [unix]
    - eigen
  run:
    - postgresql ==9.5
    - ncurses

about:
  home: http://rdkit.org
  license: BSD
