package:
  name: rdkit
  version: "__conda_version__"

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_rev: Release_2017_03
  patches:
    - rdpaths.patch
    - rdconfig.patch [win]

build:
  number: 1

requirements:
  build:
    - cmake
    - requests
    - boost ==1.61.0 [unix]
    - boost ==1.56.0 [win and py27]
    - boost ==1.56.0 [win and py34]
    - boost ==1.59.0 [win and py35]
    - boost ==1.59.0 [win and py36]
    - python
    - numpy {{ '%s.*' % (environ.get('NPY_VER') or '1.11') }}
    - pillow
    - freetype
    - nox [unix]
    - cairo [unix]
    - pkg-config [unix]
    - eigen
    - pandas
    - m2-patch [win]
  run:
    - boost ==1.61.0 [unix]
    - boost ==1.56.0 [win and py27]
    - boost ==1.56.0 [win and py34]
    - boost ==1.59.0 [win and py35]
    - boost ==1.59.0 [win and py36]
    - cairo [unix]
    - python
    - pillow
    - pandas
    - numpy {{ '%s.*' % (environ.get('NPY_VER') or '1.11') }}

test:
  imports:
    - rdkit

about:
  home: http://rdkit.org
  license: BSD
