package:
  name: rdkit
  # This is the real version, used in releases:
  # version is the last TAG + the number of commits since
  # version: {{ environ.get('GIT_DESCRIBE_TAG', 'LOCAL').replace("_", ".").replace("Release.","") }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # This is the version used for the nightlies:
  version: 2018.09.1pre.{{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}


source:
  git_url: https://github.com/rdkit/rdkit.git
  git_rev: master
  patches:
    - rdpaths.patch
    - rdconfig.patch [win]

build:
  number: 1

requirements:
  build:
    - requests
    - {{ compiler('cxx') }}
    - python
    - m2-patch [win]
    - cmake
  host:
    - boost-cpp ==1.65.1
    - py-boost ==1.65.1
    - python
    - numpy ==1.12
    - pillow
    - freetype
    - nox [linux]
    - cairo ==1.14.6 [linux]
    - cairo [not linux]
    - pkg-config [unix]
    - eigen
    - pandas <=0.22.0
  run:
    - py-boost ==1.65.1
    - cairo
    - python
    - pillow
    - pandas
    - numpy >=1.12
test:
  imports:
    - rdkit

about:
  home: http://rdkit.org
  license: BSD
