package:
  name: rdkit
  version: "__conda_version__"

source:
  git_url: https://github.com/rdkit/rdkit.git
  git_branch: master
  patches:
    - rdpaths.patch

build:
  number: 0 

requirements:
  build:
    - cmake
    - requests
    - boost ==1.56.0 [unix]
    - boost ==1.56.0 [win and py27]
    - boost ==1.56.0 [win and py34]
    - boost ==1.59.0 [win and py35]
    - inchi
    - python
    - numpy {{ '%s.*' % (environ.get('NPY_VER') or '1.10') }}
    - pillow
    - freetype
    - cairocffi [linux]
    - pandas
  run:
    - boost ==1.56.0 [unix]
    - boost ==1.56.0 [win and py27]
    - boost ==1.56.0 [win and py34]
    - boost ==1.59.0 [win and py35]
    - inchi
    - python
    - numpy {{ '%s.*' % (environ.get('NPY_VER') or '1.10') }}

test:
  imports:
    - rdkit

about:
  home: http://rdkit.org
  license: BSD
